# -*- coding: utf-8 -*-
"""DLHSWeek01.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1slE-9wpcxBzb1bXixo90UuSKzMC2Pap0

# 1 Xác định và phân loại dữ liệu định tính và định lượng
"""

import pandas as pd

df = pd.read_csv('processed_dulieuxettuyendaihoc.csv')

print("Các cột dữ liệu:\n")
print(df.dtypes)

print("\nCác cột định lượng:")
print(df.select_dtypes(include=['int64', 'float64']).columns)

print("\nCác cột định tính:")
print(df.select_dtypes(include=['object']).columns)

"""# 2. Định nghĩa các thang đo phù hợp cho từng biến số

"""

nominal = ['GT', 'KV', 'KT']
ordinal = ['XL1', 'XL2', 'XL3']
quantitative = [
    'T1', 'L1', 'H1', 'S1', 'V1',
    'TBM1', 'TBM2', 'TBM3',
    'US_TBM1', 'US_TBM2', 'US_TBM3',
    'KQXT'
]

print("Biến định danh (Nominal):")
print(nominal)

print("\nBiến thứ bậc (Ordinal):")
print(ordinal)

print("\nBiến định lượng:")
print(quantitative)

"""# 3. Sử dụng Python để tải dữ liệu lên chương trình và in ra màn hình 10 dòng đầu tiên và 10 dòng cuối cùng"""

# In 10 dòng đầu tiên
print("10 dòng đầu tiên:")
print(df.head(10))

# In 10 dòng cuối cùng
print("\n10 dòng cuối cùng:")
print(df.tail(10))

"""# 4. Thống kê dữ liệu thiếu cho cột dân tộc và hiệu chỉnh dữ liệu thiếu như sau: Mặc định thiếu thì điền giá trị 0.
Hướng dẫn
1. Lập bảng tần số, tần suất để khảo sát dữ liệu thiếu, bao nhiêu dữ liệu riêng biệt (pandas
unique)
2. Thực hiện thay thế dữ liệu thiếu bằng phương pháp điền dữ liệu 0
"""

# Kiểm tra dữ liệu thiếu của cột DT

print("Số lượng dữ liệu thiếu:")
print(df['DT'].isnull().sum())

print("\nCác giá trị riêng biệt:")
print(df['DT'].unique())

print("\nBảng tần số:")
print(df['DT'].value_counts(dropna=False))

print("\nBảng tần suất:")
print(df['DT'].value_counts(normalize=True, dropna=False))

"""# 5. Thống kê dữ liệu thiếu cho biến T1 và hiệu chỉnh dữ liệu, lưu ý việc thay thế dữ liệu thiếu sử dụng phương pháp Mean.
Hướng dẫn
1. Lập bảng tần số, tần suất để khảo sát dữ liệu thiếu
2. Thực hiện thay thế dữ liệu thiếu bằng phương pháp Mean
"""

print("Số lượng dữ liệu thiếu:")
print(df['T1'].isnull().sum())

print("\nCác giá trị riêng biệt:")
print(df['T1'].unique())

print("\nBảng tần số:")
print(df['T1'].value_counts(dropna=False))

print("\nBảng tần suất:")
print(df['T1'].value_counts(normalize=True, dropna=False))

"""# 6. Hãy thực hiện xử lý lần lượt tất cả dữ liệu thiếu cho các biến về điểm số còn lại."""

# Danh sách các cột điểm số

score_columns = [
    'T1', 'L1', 'H1', 'S1', 'V1', 'X1', 'D1', 'N1',
    'T2', 'L2', 'H2', 'S2', 'V2', 'X2', 'D2', 'N2',
    'T3', 'L3', 'H3', 'S3', 'V3', 'X3', 'D3', 'N3',
    'T4', 'L4', 'H4', 'S4', 'V4', 'X4', 'D4', 'N4',
    'T5', 'L5', 'H5', 'S5', 'V5', 'X5', 'D5', 'N5',
    'T6', 'L6', 'H6', 'S6', 'V6', 'X6', 'D6', 'N6',
    'TBM1', 'TBM2', 'TBM3',
    'US_TBM1', 'US_TBM2', 'US_TBM3',
    'KQXT'
]

# Xử lý dữ liệu thiếu bằng Mean

for col in score_columns:

    missing_before = df[col].isnull().sum()
    mean_value = df[col].mean()

    df[col] = df[col].fillna(mean_value)

    missing_after = df[col].isnull().sum()

    print(f"Cột {col}:")
    print(f" - Missing trước xử lý: {missing_before}")
    print(f" - Mean: {mean_value}")
    print(f" - Missing sau xử lý: {missing_after}")
    print()

"""# 7. Tạo các biến TBM1, TBM2, TBM3 tương ứng với trung bình môn của các năm lớp 10, 11 và 12.  
• Công thức tính: TBM = (T*2 + L + H + S + V*2 + X + D + N) / 10
"""

# Tạo biến TBM1 cho lớp 10

df['TBM1'] = (
    df['T1'] * 2 +
    df['L1'] +
    df['H1'] +
    df['S1'] +
    df['V1'] * 2 +
    df['X1'] +
    df['D1'] +
    df['N1']
) / 10

# Tạo biến TBM2 cho lớp 11

df['TBM2'] = (
    df['T2'] * 2 +
    df['L2'] +
    df['H2'] +
    df['S2'] +
    df['V2'] * 2 +
    df['X2'] +
    df['D2'] +
    df['N2']
) / 10

# Tạo biến TBM3 cho lớp 12

df['TBM3'] = (
    df['T3'] * 2 +
    df['L3'] +
    df['H3'] +
    df['S3'] +
    df['V3'] * 2 +
    df['X3'] +
    df['D3'] +
    df['N3']
) / 10

# Hiển thị kết quả

print(df[['TBM1', 'TBM2', 'TBM3']].head(10))

"""# 8. Tạo các biến xếp loại XL1, XL2 và XL3 dựa trên TBM1, TBM2 và TBM3
• Nhỏ hơn 5.0 xếp loại: yếu (kí hiệu là Y)
• Từ 5.0 đến dưới 6.5: trung bình (kí hiệu là TB)
• Từ 6.5 đến dưới 8.0: khá (kí hiệu là K)
• Từ 8.0 đến dưới 9.0: giỏi (kí hiệu là G)
• Từ 9.0 trở lên: xuất sắc (kí hiệu là XS)
"""

# Hàm xếp loại học lực

def xep_loai(tbm):

    if tbm < 5.0:
        return 'Y'

    elif tbm < 6.5:
        return 'TB'

    elif tbm < 8.0:
        return 'K'

    elif tbm < 9.0:
        return 'G'

    else:
        return 'XS'


# Tạo các cột xếp loại

df['XL1'] = df['TBM1'].apply(xep_loai)
df['XL2'] = df['TBM2'].apply(xep_loai)
df['XL3'] = df['TBM3'].apply(xep_loai)

# Hiển thị kết quả

print(df[['TBM1', 'XL1', 'TBM2', 'XL2', 'TBM3', 'XL3']].head(10))

"""# 9. Tạo các biến US_TBM1, US_TBM2 và US_TBM3 để chuyển điểm trung bình các năm lớp 10, 11 và 12 từ thang điểm 10 của Việt Nam sang thang điểm 4 của Mỹ. Sử dụng phương pháp Min-Max Normalization"""

# Chuyển đổi từ thang điểm 10 sang thang điểm 4

df['US_TBM1'] = (df['TBM1'] / 10) * 4
df['US_TBM2'] = (df['TBM2'] / 10) * 4
df['US_TBM3'] = (df['TBM3'] / 10) * 4

# Hiển thị kết quả

print(df[['TBM1', 'US_TBM1',
          'TBM2', 'US_TBM2',
          'TBM3', 'US_TBM3']].head(10))

"""# 10. Tạo biến kết quả xét tuyển (kí hiệu là KQXT) nhằm xác định sinh viên đậu (giá trị “1”) và rớt ( giá trị “0”) vào các khối dựa trên điểm DH1, DH2 và DH3 như sau
• Với khối A, A1 nếu [(DH1*2 + DH2 + DH3)/4] lớn hơn hoặc bằng 5.0 thì đậu,
ngược lại là rớt

• Với khối B nếu [(DH1 + DH2*2 + DH3)/4] lớn hơn hoặc bằng 5.0 thì đậu, ngược
lại là rớt

• Với khối khác nếu [(DH1+ DH2 + DH3)/3] lớn hơn hoặc bằng 5.0 thì đậu, ngược
lại là rớt
"""

# Hàm xét tuyển

def xet_tuyen(row):

    khoi = row['KT']

    # Khối A, A1
    if khoi in ['A', 'A1']:

        diem = (row['DH1'] * 2 + row['DH2'] + row['DH3']) / 4

    # Khối B
    elif khoi == 'B':

        diem = (row['DH1'] + row['DH2'] * 2 + row['DH3']) / 4

    # Các khối khác
    else:

        diem = (row['DH1'] + row['DH2'] + row['DH3']) / 3


    # Xét đậu/rớt
    if diem >= 5.0:
        return 1
    else:
        return 0


# Tạo cột KQXT

df['KQXT'] = df.apply(xet_tuyen, axis=1)

# Hiển thị kết quả

print(df[['KT', 'DH1', 'DH2', 'DH3', 'KQXT']].head(10))

"""# 11. Lưu trữ dữ liệu xuống ổ đĩa thành file processed_dulieuxettuyendaihoc.csv"""

import os

output_path = Path(__file__).parent / "processed_dulieuxettuyendaihoc.csv"

df.to_csv(str(output_path), index=False, encoding='utf-8-sig')

print("Saved:", output_path)

print("Đã lưu file processed_dulieuxettuyendaihoc.csv thành công")